### ISSUE TITLE
Create a requirments.txt file

### ISSUE THREAD

**Issue by satyaakam** [OpenMOOC/moocng#16]
hi,
    i could not locate rquirements.txt file while installing , we need to have a reuirements.txt file for installing.

-Satya

**Comment by pitbulk** [comment]
Hi, in the setup.py you will find the 'install_requires' var that contains the dependences.

We work with virtualenv, checkout the installation and configuration documentation (docs folder)

**Comment by lorenzogil** [comment]
What pitbulk means is that you can install the project using easy_install instead of pip.

Feel free to convert the dependencies in the setup.py file into a requirements.txt _and_ modify the setup.py so it read this file and put it in the install_requires variable. That would be a good contribution that will be accepted.

**Comment by satyaakam** [comment]
thanks figured this out after i created the ticket , let me first get my MOOC running
